




spring:
  datasource:
    url: jdbc:mysql://${DB_SERVER:169.51.195.164}:${DB_PORT:30354}/${DB_NAME:demo}?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC
    driverClassName: com.mysql.cj.jdbc.Driver
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:admin1234}


mybatis:
  mapper-locations: classpath:mapper/exchange/*Mapper.xml
  configuration:
    map-underscore-to-camel-case: true
