apiVersion: v1
kind: ConfigMap
metadata:
  name: config
data:
  SERVLET_CONTEXT_PATH: "/"
# MYSQL DB
  DB_SERVER: db-practicum-mariadb-primary 
  DB_PORT: "3306"
  DB_USERNAME: root
  DB_PASSWORD: Passw0rd!
